id = "optima-theme"
name = "Optima Theme"
version = "0.0.1"
schema_version = 1
authors = ["Iftekhar"]
description = "A beautiful dark minimal theme for Zed editor"
repository = "https://github.com/iftekhar-ifat/optima-theme"
